### ISSUE TITLE
sh: 1: pause: not found

### ISSUE THREAD

**Issue by hmsjy2017** [Nyarime/qcloud-lighthouse-discount#1]
Linux 下报错
![7D8254FA-8DD9-40B9-8BCD-B66CCF59A2A6](https://user-images.githubusercontent.com/42692274/155865580-51e3a1e3-e8d8-413e-81aa-61c07ed50f66.jpeg)

**Comment by nyarime** [comment]
在DOS命令中有一个命令是pause，它的作用是输出提示信息"Press any key to continue...“ ，然后用户随意敲一个键后程序继续运行。 pause 它会提示“请按任意键继续...” ，pause命令没有任何的参数，它的命令就是它的本身，当pause命令运行后，会中断执行的语句。

**Comment by nyarime** [comment]
另外续费价格需要低于代金券的最低付费门槛，不然数值会提示不正确

**Comment by hmsjy2017** [comment]
@Nyarime Linux 中没有 pause 命令，可以在 Linux 中使用`read -n 1`代替
